--What is the most reprinted story for an issue? Display the issue ID, the story ID with the most reprints, and the
--corresponding reprint count. Sort the output based on the reprint count, and display the top 5 results. Count only
--the immediate reprints (the stories that match the origin ID).
--Output schema: {Issue ID, Story ID, Count} 
