--List all Marvel heroes that appear in Marvel-DC story crossovers. Marvel and DC are considered to be (parts of)
--Indicia Publisher names, and the heroes are described in the story feature attribute. Therefore, we are interested
--in heroes that appear in purely Marvel stories (without DC) AND in the ones that have both Marvel and DC in the
--corresponding Indicia publisher name. When comparing strings, you must transform all the strings to lowercase
--(there is a corresponding function to use – check the documentation) and use partialstring matches – so for Marvel
--and DC you need to find Indicia Publishers that partially match ’marvel’ and ’dc’ anywhere in the string. Display
--distinct, lowercase hero/feature strings – but do not manually deduplicate them further. Make sure that in the final
--result once you combine purely Marvel heroes with crossover heroes, you match their names partially as well!
--Output schema: {Crossover Feature Heroes} 